sources:
  - name: staging
    database: de-zoomcamp-2024-418900
    schema: week4

    tables:
      - name: green_tripdata
      - name: yellow_tripdata

models:
  - name: stg_green_tripdata
    description: ""
    columns:
      - name: tripid
        data_type: string
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
  - name: stg_yellow_tripdata
    description: ""
    columns:
      - name: tripid
        data_type: string
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
